### ISSUE TITLE
Handle Postgres 'NULL' types

### ISSUE THREAD

**Issue by fresonn** [sqlc-dev/sqlc#1097]
Hey!
For example, I have a schema
```sql
CREATE TYPE tag AS ENUM ('new', 'stock', 'top');

CREATE TABLE some_table (
    ...
    mainTag tag
    ...
)
```
You can see that the _mainTag_ field in the table can be **null**.
And for the corresponding table, 'sqlc' generates me the following code
```go
type TagType string

const (
	TagTypeNew   TagType = "new"
	TagTypeStock TagType = "stock"
	TagTypeTop     TagType = "top"
)

func (e *TagType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TagType(s)
	case string:
		*e = TagType(s)
	default:
		return fmt.Errorf("unsupported scan type for TagType: %T", src)
	}
	return nil
}
```

After I try to translate data from the database, I always get an error in the default case: "unsupported scan type for ...."

Question.
SQLC can track that this field can have a **NULL** value in the schema?

**Comment by kyleconroy** [comment]
I think the best option here to generate a second type that can handle NULL values. This will also be backwards compatible with the existing type.

```go
type NullTagType struct {
    TagType TagType
    Valid bool
}
```

**Comment by sbres** [comment]
I'm looking at this problem and I think I can try at least scope out the work needed.

In order to replicate the Nullable values form the SQL library, wee need the equivalent of `convertAssignRows`
After looking at some PR https://github.com/golang/go/issues/24258 for example it is clear the method will stay private.
It is not possible to only copy-paste the method as I found it not that easy to extract it.
This library has the equivalent function but is easy to copy paste:
https://github.com/denisenkom/go-mssqldb/blob/master/convert.go

1- We need an equivalent to convertAssign.
Should we add a convert.go file on the generation with convertAssign from go-mssqldb ?
Should we add convertAssign to sqlc as a public method ?

2- Once we have convertAssign we can create the NullXXX type needed with it's equivalent Scan and Value methods
Should we generate this type even when the type is never used? 
If we can just generate it no matter what becomes very straightforward.

3- Use the Nullable value instead of the raw type on the needed queries
I actually have not vision on this part at all.

@kyleconroy If you can tell me what you prefer for the point N-1 I can try to draft a PR with the changes, at least the points 1, 2

**Comment by Jille** [comment]
@sbres I'm not sure why we need a copy of convertAssign at all? Shouldn't implementing driver.Valuer be enough?

I've drafted up a PR, #1582. It seemed fairly simple, but I haven't even tried to execute the code yet.

**Comment by sbres** [comment]
I had forgotten about this comment. Yeah, we don't need the convertAssign.
I've also made a PR for this issue 
https://github.com/kyleconroy/sqlc/pull/1485

**Comment by kyleconroy** [comment]
sqlc now generates the correct Null* types for enums.
