### ISSUE TITLE
Ignore certain tables when generating code

### ISSUE THREAD

**Issue by glen-edmonds** [sqlc-dev/sqlc#1380]
I have many intermediate/db-internal table/views/etc that the Go code doesn't need to know about and this results in clutter.

I could not find anything in the documentation for how to ignore certain tables when generating Go code.

Create a way blacklist certain entities.

**Comment by kyleconroy** [comment]
sqlc understands DDL statements and can take multiple paths for schema. The easiest way to ignore certain tables is to delete them. Create a separate folder for the DDL statements so that you don't accidentally run them against your production database. Then add a `DELETE {table}` statement for each table you want to ignore.

Can you try that out and let me know if it works?

**Comment by josharian** [comment]
I have a similar issue. I'm trying to separate groups of tables into separate Go packages. This is easy enough--run `sqlc generate` with a different `sqlc.yaml` and `query.sql` in a different directory. But this generates lots of extraneous code. Using `DELETE` statements to get rid of the cruft means that if I add a table, I then have to delete it in multiple places.

I'd rather have an allowlist. Then when I add a new table, I add it to the allowlist just in the packages where it is relevant.

As usual, I'd be happy to implement, if I can get design feedback.

**Comment by kyleconroy** [comment]
The `omit_unused_structs` option can drop any structs that aren't used by queries https://docs.sqlc.dev/en/stable/reference/config.html
