### ISSUE TITLE
Column type `string` does not return error

### ISSUE THREAD

**Issue by mohdrasbi** [sqlc-dev/sqlc#1917]
### Version

1.15.0

### What happened?

When a create a table with a column type `string`, which is not a postgres datatype:

```
create table test_table (
    id string
);
```

the sqlc code generator **does not** return any errors. It generates a field in Go with type `string`.

However, when the migration is applied, an error is returned since the datatype `string` does not exist in postgres.

### Playground URL

https://play.sqlc.dev/p/377ff1e3c1bac823de845bd66dbffbee9ed4bb328e63f7c291297c6d256c7112

**Comment by kyleconroy** [comment]
This is fixed in [v1.23.0](https://docs.sqlc.dev/en/latest/reference/changelog.html#v1-23-0) by enabling the [database-backed query analyzer](https://docs.sqlc.dev/en/latest/howto/generate.html#enhanced-analysis-with-managed-databases). We added a [test case](https://github.com/sqlc-dev/sqlc/tree/main/internal/endtoend/testdata/ddl_create_table_unknown_type/postgresql/pgx) for this issue so it won’t break in the future.

You can play around with the [working example on the playground](https://play.sqlc.dev/p/a27375ca52ef079bac1aec62e7d0822a3cb18b7ea33a6401ae4ebce111cb2b60)
