### ISSUE TITLE
Nested WITH doesn't work

### ISSUE THREAD

**Issue by hugosjoberg** [sqlc-dev/sqlc#2226]
### Version

1.17.2

### What happened?

When a WITH is nested it doesn't work. The query works when running the query directly against postgres but fails when running in SQLC.

### Relevant log output

```shell
/query.sql:9:1: relation "summary" does not exist
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
WITH person AS(
    WITH summary AS(
        WITH mb AS(
            select
                *
            from authors
        )
        SELECT
            bio
        FROM mb
        )
    SELECT
       count(*)
    FROM summary
)

select * from person;
```

### Playground URL

https://play.sqlc.dev/p/e3b1e1370d95e38ad655fb46b019f20172272b6298e112ee9bf770878979bd00

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
This is fixed in [v1.23.0](https://docs.sqlc.dev/en/latest/reference/changelog.html#v1-23-0) by enabling the [database-backed query analyzer](https://docs.sqlc.dev/en/latest/howto/generate.html#enhanced-analysis-with-managed-databases). We added a [test case](https://github.com/sqlc-dev/sqlc/tree/main/internal/endtoend/testdata/cte_nested_with/postgresql/pgx) for this issue so it won’t break in the future.

You can play around with the [working example on the playground](https://play.sqlc.dev/p/d1a6ba8bfe7cb2fe0410b6997ca424fd436edcf3128c98135e0e345832cd42c8)
