### ISSUE TITLE
Adjusting the codegen handler order

### ISSUE THREAD

**Issue by topazur** [sqlc-dev/sqlc#2716]
### Version

1.21.0

### What happened?

repo: [sqlc-gen-go-separate](https://github.com/topazur/sqlc-gen-go-separate)

I have created a plugin with the aim of changing the `codegen/golang` templates to meet my project requirements.

But I found that due to the order of the handlers, I cannot use the `config.SQLGen` field in the configuration item.

I think we should lower the priority of `golang.Generate`.

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by topazur** [comment]
Hello!
I think the default generator priority should be the lowest, I don't know what you think about this? 
This way, I have more possibilities for operation in the plugin configuration file.

**Comment by kyleconroy** [comment]
@topazur I misunderstood this issue when it was originally opened. We'll get this in for 1.23.0

**Comment by andrewmbenton** [comment]
I pushed a PR that I think resolves this issue.

But @topazur just so you're aware, we will be deprecating the go-specific configuration options from the codegen request proto in the near future.

**Comment by topazur** [comment]
@andrewmbenton Thank you, I will continue to follow the configuration options!

**Comment by andrewmbenton** [comment]
@topazur after doing some more testing related to extracting our Go codegen as a plugin, I realized I may not understand exactly what is going wrong for you.

>  cannot use the `config.SQLGen` field in the configuration item

Can you expand on this a little bit? Are you saying that inside of your plugin, you don't have access to the configuration options from the built-in go codegen as parsed from `sqlc.yaml`? Because all of those options are parsed and sent to every plugin, as part of the codegen request proto (although as mentioned we will likely be removing them). The codegen request has a `Settings` field with a `GoCode` field underneath, which has all of the configured options: https://buf.build/sqlc/sqlc/docs/main:plugin#plugin.GoCode.

But maybe there is another problem?
