### ISSUE TITLE
emit_exported_queries Improvement

### ISSUE THREAD

**Issue by safaci2000** [sqlc-dev/sqlc#2940]
### What do you want to change?

Current when `emit_exported_queries` is enabled, the query is exposed with the comment included, 

Example:

```go
const CreateNewTask = `-- name: CreateNewTask :one
INSERT into tasks.task (task_reference, context_id, task_type, task_status, task_data)
VALUES ($1, $2, $3, $4, $5) RETURNING task_id
```

It would be nice to have a pattern where it strips away the comment.  In order to create a dynamic query and utilize the SQL generated with say a query builder or such I'd need to remove the comment programmatically.

### What database engines need to be changed?

PostgreSQL, MySQL, SQLite

### What programming language backends need to be changed?

Go

**Comment by andrewmbenton** [comment]
The query comment is ignored by the underlying database, so I think there should be no need to remove it unless the query builder can't handle it.

In any case, this is probably a good case for forking and modifying [sqlc-gen-go](https://github.com/sqlc-dev/sqlc-gen-go) rather than adding a configuration parameter for all sqlc users.

**Comment by safaci2000** [comment]
Fair enough.  If I fork the sqlc-gen-go, is it possible to point SQLC to my own version that code ?

**Comment by andrewmbenton** [comment]
> Fair enough. If I fork the sqlc-gen-go, is it possible to point SQLC to my own version that code ?

Yes, you can use it like any other sqlc plugin. Instructions are in the sqlc-gen-go readme.
