### ISSUE TITLE
Missing check for update on PostgreSQL

### ISSUE THREAD

**Issue by ghost** [sqlc-dev/sqlc#884]
The following query is compiled, although it should not, since the `is_deleted` column does not exist.

```sql
UPDATE
	public.articles
SET
	is_deleted = TRUE
WHERE
	id = $1;
```

Schema:
```sql
CREATE TABLE public.articles (
    id integer NOT NULL,
    company integer NOT NULL,
    name text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    object_type smallint NOT NULL,
    image text,
    "group" integer,
    notes text DEFAULT ''::text NOT NULL
);
``` 

I am using PostgreSQL 13.

https://play.sqlc.dev/p/3b7f89f370c2d2f1aff72fb0953a00d98d52ec2cc195d848dca81cacec4c3344

**Comment by kyleconroy** [comment]
This is fixed in [v1.23.0](https://docs.sqlc.dev/en/latest/reference/changelog.html#v1-23-0) by enabling the [database-backed query analyzer](https://docs.sqlc.dev/en/latest/howto/generate.html#enhanced-analysis-with-managed-databases). We added a [test case](https://github.com/sqlc-dev/sqlc/tree/main/internal/endtoend/testdata/invalid_update_unknown_column/postgresql/pgx) for this issue so it won’t break in the future.

You can play around with the [working example on the playground](https://play.sqlc.dev/p/53a82da8a2eac16d02ddb3120823054530ac4846818844e48c8000cbc99828e7)
